services:
  app:
    build: .
    tty: true
    networks:
      - todo_network
    ports:
      - "3003:3000"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    depends_on:
      - db2
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:5432/${DB_NAME}"


  db2:
    image: postgres:15
    hostname: db2
    env_file:
      - ./.env
    networks:
      - todo_network
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

networks:
  todo_network:
    driver: bridge

volumes:
  node_modules:
  db_data:
